// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqnuFg1bdbWAI2FNzhRagr0v5vqWdvi4',
    appId: '1:671873550792:web:cafc22a665cde341d218fd',
    messagingSenderId: '671873550792',
    projectId: 'coms-01',
    authDomain: 'coms-01.firebaseapp.com',
    storageBucket: 'coms-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNTZ-QiRWyz3YVimEMTpnadHVvP7XH7eg',
    appId: '1:671873550792:android:8ffd3d105b8c5bc6d218fd',
    messagingSenderId: '671873550792',
    projectId: 'coms-01',
    storageBucket: 'coms-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_y0nuCXcuFVwl_sP4_M9af4n91OxQAmA',
    appId: '1:671873550792:ios:28721a63c775dd91d218fd',
    messagingSenderId: '671873550792',
    projectId: 'coms-01',
    storageBucket: 'coms-01.firebasestorage.app',
    iosClientId: '671873550792-45tl6p817s7o743ngm6dp6a80hj6uj7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_y0nuCXcuFVwl_sP4_M9af4n91OxQAmA',
    appId: '1:671873550792:ios:28721a63c775dd91d218fd',
    messagingSenderId: '671873550792',
    projectId: 'coms-01',
    storageBucket: 'coms-01.firebasestorage.app',
    iosClientId: '671873550792-45tl6p817s7o743ngm6dp6a80hj6uj7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbqnuFg1bdbWAI2FNzhRagr0v5vqWdvi4',
    appId: '1:671873550792:web:366e6292839eb08fd218fd',
    messagingSenderId: '671873550792',
    projectId: 'coms-01',
    authDomain: 'coms-01.firebaseapp.com',
    storageBucket: 'coms-01.firebasestorage.app',
  );

}